import { AsyncBoundary } from '@data-client/react';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Link from 'next/link';

import styles from './page.module.css';
import Provider from './Provider';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={styles.page}>
          <nav className={styles.topNav}>
            <Link href="/">Coin</Link>
          </nav>
          <main className={styles.main}>
            <Provider>
              <AsyncBoundary>{children}</AsyncBoundary>
            </Provider>
          </main>
        </div>
      </body>
    </html>
  );
}
